#!/usr/bin/env bash
# =============================================================================
# phases/05_migrate_config.sh
# Migrate: config validation system from v0.1.57 into a NEW src/core/config/
# This entire module is net-new to nexus-search v0.3.0.
# Files:
#   NexusSearchConfig.ts  — main config class
#   defaults.ts           — default config values
#   interfaces.ts         — config interface declarations
#   validation.ts         — config validator → renamed ConfigValidator.ts
# =============================================================================
set -euo pipefail
source "$(dirname "$0")/../lib/common.sh"
guard_repos

phase "05 — Configuration Module Migration (net-new src/core/config/)"

mkdir -p "$TARGET_SRC/core/config"

step "NexusSearchConfig — main config class"
additive_copy \
  "$NOFS_SRC/config/NexusSearchConfig.ts" \
  "$TARGET_SRC/core/config/NexusSearchConfig.ts" \
  "NexusSearchConfig.ts"

step "defaults — default configuration values"
additive_copy \
  "$NOFS_SRC/config/defaults.ts" \
  "$TARGET_SRC/core/config/defaults.ts" \
  "defaults.ts"

step "interfaces — config interface declarations"
additive_copy \
  "$NOFS_SRC/config/interfaces.ts" \
  "$TARGET_SRC/core/config/interfaces.ts" \
  "interfaces.ts"

step "validation → ConfigValidator (renamed for clarity)"
additive_copy \
  "$NOFS_SRC/config/validation.ts" \
  "$TARGET_SRC/core/config/ConfigValidator.ts" \
  "ConfigValidator.ts  (renamed from validation.ts)"

step "Generate config barrel: src/core/config/index.ts"
CONFIG_INDEX="$TARGET_SRC/core/config/index.ts"
if [[ ! -f "$CONFIG_INDEX" ]]; then
  if [[ "$DRYRUN" == "1" ]]; then
    info "[DRY-RUN] would write $CONFIG_INDEX"
  else
    cat > "$CONFIG_INDEX" << 'EOF'
// src/core/config/index.ts
// Auto-generated by 05_migrate_config.sh — review and adjust as needed
export * from './NexusSearchConfig';
export * from './defaults';
export * from './interfaces';
export * from './ConfigValidator';
EOF
    ok "config/index.ts  (barrel generated)"
  fi
else
  warn "config/index.ts already exists — skipping barrel generation"
fi

print_summary "Phase 05 — Config"
